/**
 * Name of the Nx plugin.
 */
export const NX_PLUGIN_NAME = 'nx-flutter';

/**
 * Scope of the Nx plugin.
 */
export const NX_PLUGIN_SCOPE = '@flutter-starter';

/**
 * Package name of the Nx plugin.
 */
export const NX_PLUGIN_PACKAGE = `${NX_PLUGIN_SCOPE}/${NX_PLUGIN_NAME}`;

/**
 * Default Flutter CLI arguments for each command.
 */
export const DEFAULT_FLUTTER_CLI_ARGS = {
  create: {
    description: 'A new Flutter application.',
    org: 'com.example',
    platforms: ['android', 'ios', 'linux', 'windows', 'macos', 'web'],
    androidLanguage: 'kotlin',
    iosLanguage: 'swift',
    pub: true,
    offline: false,
    overwrite: false,
    empty: false,
  },
  analyze: {
    verbose: false,
    currentPackage: true,
    watch: false,
    write: undefined,
    suggestions: true,
    pub: true,
    congratulate: true,
    preamble: true,
    fatalInfos: true,
    fatalWarnings: true,
  },
  attach: {
    verbose: false,
    deviceId: undefined,
    mode: 'debug',
    target: undefined,
    deviceVmservicePort: 0,
    hostVmservicePort: 0,
    dartDefine: [] as string[],
    dartDefineFromFile: undefined,
    deviceUser: undefined,
    nullAssertions: true,
    debugUrl: undefined,
    appId: undefined,
    pidFile: undefined,
    trackWidgetCreation: true,
    ddsPort: 0,
    deviceTimeout: 10,
  },
  clean: {
    verbose: false,
  },
  genL10n: {
    verbose: false,
    arbDir: 'lib/l10n',
    outputDir: undefined,
    templateArbFile: 'app_en.arb',
    untranslatedMessagesFile: undefined,
    outputClass: 'AppLocalizations',
    preferredSupportedLocales: [],
    header: undefined,
    headerFile: undefined,
    useDeferredLoading: true,
    genInputsAndOutputsList: undefined,
    syntheticPackage: true,
    projectDir: undefined,
    requiredResourceAttributes: true,
    nullableGetter: true,
    format: true,
    useEscaping: true,
    suppressWarnings: true,
  },
  install: {
    verbose: false,
    deviceId: undefined,
    mode: 'debug',
    useApplicationBinary: undefined,
    flavor: undefined,
    deviceTimeout: 10,
    deviceUser: undefined,
    uninstallOnly: false,
  },
  run: {
    verbose: false,
    deviceId: undefined,
    mode: 'debug',
    dartDefine: [] as string[],
    dartDefineFromFile: undefined,
    flavor: undefined,
    webRenderer: 'auto',
    useApplicationBinary: undefined,
    traceStartup: false,
    cacheStartupProfile: true,
    verboseSystemLogs: false,
    cacheSksl: false,
    dumpSkpOnShaderCompilation: false,
    purgePersistentCache: false,
    route: undefined,
    startPaused: true,
    endlessTraceBuffer: false,
    traceSystrace: false,
    traceSkia: false,
    enableDartProfiling: true,
    enableSoftwareRendering: false,
    skiaDeterministicRendering: false,
    dartEntrypointArgs: [] as string[],
    webLaunchUrl: undefined,
    target: undefined,
    deviceVmservicePort: 0,
    hostVmservicePort: 0,
    pub: true,
    trackWidgetCreation: true,
    nullAssertions: true,
    deviceUser: undefined,
    deviceTimeout: 10,
    ddsPort: 0,
    androidProjectArg: [] as string[],
    multidex: true,
    ignoreDeprecation: false,
    awaitFirstFrameWhenTracing: true,
    useTestFonts: true,
    build: true,
    hot: true,
    pidFile: undefined,
  },
  test: {
    verbose: false,
    deviceId: undefined,
    pub: true,
    nullAssertions: true,
    trackWidgetCreation: true,
    dartDefine: [] as string[],
    dartDefineFromFile: undefined,
    webRenderer: 'auto',
    deviceUser: undefined,
    flavor: undefined,
    name: undefined,
    plainName: undefined,
    tags: [] as string[],
    excludeTags: [] as string[],
    startPaused: true,
    runSkipped: false,
    coverage: false,
    mergeCoverage: false,
    branchCoverage: false,
    coveragePath: undefined,
    updateGoldens: false,
    concurrency: undefined,
    testAssets: true,
    testRandomizeOrderingSeed: undefined,
    totalShards: undefined,
    shardIndex: undefined,
    reporter: 'compact',
    timeout: undefined,
    ddsPort: 0,
  },
};
