import { FlutterProjectGeneratorOptions } from '../../lib/models/flutter-project-generator-options.model';

/**
 * Flutter plugin Nx generator options.
 *
 * These are specific options passed to the `flutter create` command.
 */
export interface FlutterPluginGeneratorOptions
  extends FlutterProjectGeneratorOptions {
  /**
   * The platforms supported by the project. Platform folders (e.g. android/) will be generated in the target project. Adding desktop platforms requires the corresponding desktop config setting to be enabled.
   *
   * If not specified, all platforms are generated by the Flutter CLI.
   */
  platforms: FlutterPlatform[];

  /**
   * The language to use for Android-specific code.
   */
  androidLanguage: AndroidLanguage;

  /**
   * The language to use for iOS-specific code.
   */
  iosLanguage: IosLanguage;
}
